name: EithonBungeeFixes
main: net.eithon.plugin.bungeefixes.EithonBungeeFixes
version: ${project.version}
author: vanbrayne
permissions:
  eserver:
    description: Access to /eithonfixes eserver command
    default: op
